### ISSUE TITLE
light theme with auto complete, can not see which is selected.

### ISSUE THREAD

**Issue by jiqimaogou** [blai30/Lotus-Theme#1]
![image](https://user-images.githubusercontent.com/1407040/109387599-43a84800-793d-11eb-8a9f-3dd832e389c7.png)

**Comment by jiqimaogou** [comment]
dark is the same

**Comment by jiqimaogou** [comment]
the theme is great.

**Comment by blai30** [comment]
Does it happen all the time? What languages specifically does it happen with? I cannot reproduce it.
![image](https://user-images.githubusercontent.com/29187599/109399518-269d5600-78f8-11eb-80c6-701ff55b4ed9.png)

**Comment by jiqimaogou** [comment]
> Does it happen all the time? What languages specifically does it happen with? I cannot reproduce it.
> ![image](https://user-images.githubusercontent.com/29187599/109399518-269d5600-78f8-11eb-80c6-701ff55b4ed9.png)

oh, it's my fault, I install the material theme plugin, and I uninstall the theme is ok.
