### ISSUE TITLE
Dark Mode selection not styled 

### ISSUE THREAD

**Issue by b0wter** [blai30/Lotus-Theme#2]
I've been using Lotus Material Theme for some time now and I noticed that as of two or three Rider versions ago the code completions selection breaks if I use the arrow keys to change the selected entry.
This is what it looks like once the window opens:
![image](https://user-images.githubusercontent.com/614261/114617261-35717980-9ca8-11eb-9514-110cd9419b0a.png)
This is what it looks like after pressing arrow down:
![image](https://user-images.githubusercontent.com/614261/114617344-4c17d080-9ca8-11eb-8dc8-a5d4a55ab9e8.png)
Going back up does not fix the issue. I think it has something to do with _Material Theme UI_. After deinstalling it the window is no longer styled but works properly:
![image](https://user-images.githubusercontent.com/614261/114619529-f4c72f80-9caa-11eb-8104-72bc9ffde127.png)

Lotus Light works fine on my machine. I am running version 2021.1 on Ubuntu. Happens to me while using F# as well as C#. I've also made sure that I installed the non-Material-UI version:
![image](https://user-images.githubusercontent.com/614261/114621342-e24df580-9cac-11eb-8c7e-dc065c86f086.png)

**Comment by blai30** [comment]
Hi,

This is actually the repository for Lotus Theme (not Lotus Material Theme which is no longer maintained as JetBrains now supports theme plugins) which you are using so you are in the right place. Lotus Theme does not depend on Material Theme UI anymore. 
Currently, your third screenshot is displaying the correct colors. To be honest, I haven't looked into choosing better colors for it but that is actually how it looks.

**Comment by b0wter** [comment]
Oh, sorry for bothering you then.
The colors looked so perfect while I had Material Theme UI installed that I thought that's how it was supposed to look like. :sweat_smile: 

Do you by any chance have a reference or an idea of what the names of the fields are that are responsible for setting the colors in the code completion dialog?

**Comment by blai30** [comment]
Hey, version 1.4 of the plugin has been approved. This update includes new colors for the auto-complete menu for Lotus Dark as suggested by your issue post. Let me know how it goes

**Comment by b0wter** [comment]
Awesome! Thanks for the effort. Looks even better now :+1: 
If I may offer a suggestion, the blue highlighting the typed letters feels somewhat out of place (although that may be due to me using F# almost exclusively). You could maybe try the cyan you used for the types?
![image](https://user-images.githubusercontent.com/614261/114861562-b6865900-9ded-11eb-8a40-81bb5a614db0.png)

**Comment by blai30** [comment]
I think I'll keep it the way it is to match the accent color of the rest of the theme
