### ISSUE TITLE
Plugin error: Plugin 'Lotus Theme' (version '1.4') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is RD-212.3116.52

### ISSUE THREAD

**Issue by Fleischhauer** [blai30/Lotus-Theme#3]
Now it want's to "update" to 1.3, hmm.

**Comment by blai30** [comment]
Is this for the EAP version?

**Comment by Fleischhauer** [comment]
Yes.
Btw I downgraded to 1.3 and now I can‘t see what of the autocomplete stuff is selected.

**Comment by blai30** [comment]
I just pushed out update 1.5. The issue should be fixed now. Let me know how it goes.
https://github.com/blai30/Lotus-Theme/releases/tag/1.5

**Comment by blai30** [comment]
Version 1.5 of the plugin has been approved.
https://plugins.jetbrains.com/plugin/14369-lotus-theme
