### ISSUE TITLE
I can't see the selection in preview/intellisense

### ISSUE THREAD

**Issue by KoB-Kirito** [blai30/Lotus-Theme#4]
<img width="721" alt="Bildschirmfoto 2021-06-25 um 14 03 41" src="https://user-images.githubusercontent.com/51691757/123422266-3f73fa80-d5be-11eb-91ef-5752ca3fb050.png">
They all look the same, I don't know what's currently selected.
I'm on 2021.2 EAP 3

**Comment by blai30** [comment]
![image](https://user-images.githubusercontent.com/29187599/123470053-b69e9400-d5a8-11eb-9f72-cc82cb1c8713.png)
Seems to work fine for me on 2021.2 EAP 4.

**Comment by KoB-Kirito** [comment]
Indeed. Works again in EAP 4.
Sometimes you just have to be patient I guess..
