### ISSUE TITLE
Problems reading quick documentation

### ISSUE THREAD

**Issue by federicocl** [blai30/Lotus-Theme#5]
I'm currently working on Rubymine with Lotus Light (loving the theme btw), and when I pop the quick documentation, I can't see the description clearly. 
![lotus-light-issue](https://user-images.githubusercontent.com/75496951/125171942-376bab80-e1b7-11eb-9ad6-2305607568c5.png)

**Comment by blai30** [comment]
What versions of the IDE and the plugin are you using?

I installed the latest official version of RubyMine and using version 1.7 of Lotus Theme from the plugin marketplace. Colors look normal on my end:
![image](https://user-images.githubusercontent.com/29187599/125174325-7da21a00-e179-11eb-9d8c-9a6ee8aa079b.png)

**Comment by federicocl** [comment]
I'm using version 1.7 of the theme and the latest Rubymine version as well. 

![image](https://user-images.githubusercontent.com/75496951/125175269-42303b80-e1cb-11eb-9b35-afbe01c6443b.png)
![image](https://user-images.githubusercontent.com/75496951/125175291-5c6a1980-e1cb-11eb-9f20-585e2911879e.png)

I thought the problem was related to the theme as I didn't find any option in the settings to change that color and it didn't happen with other themes. However, seeing your screenshot I figured it could be caused by a collision with another plugin. Indeed it is, and the plugin is Material Theme UI.
With Material Theme installed:

![2021-07-10 22:14:31](https://user-images.githubusercontent.com/75496951/125175540-32195b80-e1cd-11eb-9ef5-1f937529b3bb.png)

And without it:

![2021-07-10 22:09:27](https://user-images.githubusercontent.com/75496951/125175550-41000e00-e1cd-11eb-8c65-1f3dc31bb024.png)

You might also want to know that it also bothers with auto completion as you can barely see the first option, and in the dark theme is kind of similar (both solved without Material as well):

![image](https://user-images.githubusercontent.com/75496951/125175638-bec41980-e1cd-11eb-993f-3e5dd6e14100.png)
![image](https://user-images.githubusercontent.com/75496951/125175670-ec10c780-e1cd-11eb-805e-82357369d146.png)

Greetings.

**Comment by blai30** [comment]
Unfortunately, I do not have any control over Material Theme UI

**Comment by federicocl** [comment]
I know. I just uninstalled it and everything is fine. Material is kind of popular so maybe this issue helps other people with the same problem.
