### ISSUE TITLE
somewhere, selected color is same as background with light theme

### ISSUE THREAD

**Issue by Kumome** [blai30/Lotus-Theme#6]
![image](https://user-images.githubusercontent.com/51330926/164615182-ba3d80f4-8121-48ad-bc38-a3bdec944584.png)
![image](https://user-images.githubusercontent.com/51330926/164615481-5371307d-7db5-42fa-a5a3-b622c8ad1a02.png)
![image](https://user-images.githubusercontent.com/51330926/164615499-17e94226-3c7b-4eda-bd51-a4f470c3e35f.png)

**Comment by Kumome** [comment]
By the way, it's also hard to read in breakpoint line or execution line. I changed those setting, but I can't find where to set selected color.

**Comment by blai30** [comment]
Hi, sorry for the very late response. Have you found a solution or is this still an issue?

**Comment by Kumome** [comment]
> Hi, sorry for the very late response. Have you found a solution or is this still an issue?

still an issue

**Comment by blai30** [comment]
Fixed in release 1.9.

**Comment by Kumome** [comment]
> Fixed in release 1.9.

thank you very much. now, it's easy to recognize in menu.
but there's an other dim color in code completion (pic 2, rgb #FAFAFA), when choose below suggestions.

![image](https://user-images.githubusercontent.com/51330926/174329232-673a4e25-de23-411d-88b0-daf11f766cb6.png)
![image](https://user-images.githubusercontent.com/51330926/174329350-98ec5b68-6c7f-4636-848b-bcbca315c607.png)
