### ISSUE TITLE
Lotus Material Theme ?

### ISSUE THREAD

**Issue by snoopiedoom** [blai30/Lotus-Theme#9]
[Lotus Material Theme](https://plugins.jetbrains.com/plugin/13165-lotus-material-theme) reports error `Not compatible with the version of your running IDE (CLion 2023.1.4, Rider 2023.1.3)`, but Material UI and Material Icons work just fine with [Lotus Theme](https://plugins.jetbrains.com/plugin/14369-lotus-theme) ?

**Comment by blai30** [comment]
Please do not use Lotus Material Theme as it is no longer updated. Use Lotus Theme instead.
